### PR TITLE
Add options.sourceMap

### PR DESCRIPTION
**Pull request by SneakyBobito**

### CODE REVIEW

**Comment by ericclemmons** [comment]
?

**Comment by SneakyBobito** [comment]
?

**Comment by ericclemmons** [comment]
Heh :)  You opened the PR then closed it, so I was wondering why :)

**Comment by SneakyBobito** [comment]
Because it's not merged for more than  1 month. I clean my  opened issues/PR

**Comment by ericclemmons** [comment]
Fair enough.  It's hard having lots of open-source projects, so it's easy to miss this.

**Comment by SneakyBobito** [comment]
Use this : https://github.com/issues/assigned
and this : https://github.com/pulls/assigned

:)

**Comment by ericclemmons** [comment]
Oh, I'm aware :)  There's too much on my plate with this + family + a full-time job, so I inbox-zero pending issues every month or so.

Plus, it's hard to show love towards Grunt/Gulp when they haven't been part of my team's workflow for over a year. Out of sight, out of mind, I guess. =/

Next time, instead of closing, _please_ just add a comment asking for the PR to get merged :)

**Pull request merged**
